allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
  '@fortawesome/fontawesome-common-types': false
  '@fortawesome/fontawesome-svg-core': false

peerDependencyRules:
  allowedVersions:
    magicast: 0.5.2
